### ISSUE TITLE
Add new logos to `beta-logos` package

### ISSUE THREAD

**Issue by hiletmis** [api3dao/logos#51]
**Acknowledgements**
https://github.com/api3dao/tasks/issues/445
https://github.com/api3dao/tasks/issues/479
https://github.com/nodaryio/utilities/pull/20

**To-Do**
Add the following logos;

**Commodity:**

- [ ] NG/USD

**Crypto:**

- [ ] PYTH/USD
- [ ] WOO/USD
- [ ] stETH/USD

**LSD:**

- [ ] ETHx/ETH Exchange Rate
- [ ] MATICx/MATIC Exchange Rate
- [ ] stMATIC/MATIC Exchange Rate

**Stock:**

- [ ] BABA/USD
- [ ] PYPL/USD
- [ ] QQQ/USD

**Comment by hiletmis** [comment]
https://api3dao.github.io/logos/

**Comment by hiletmis** [comment]
| Symbol Name           | Logo                                                                                                                                                |
| -----------           | --------------------------------------------------------------------------------------------------------------------------------------------------- |
| BABA                  | <img src="https://raw.githubusercontent.com/api3dao/logos/main/raw/symbols/baba.svg" width="32" height="32" /> |
| ETHx                  | <img src="https://raw.githubusercontent.com/api3dao/logos/main/raw/symbols/et-hx.svg" width="32" height="32" />  |
| MATICx                | <img src="https://raw.githubusercontent.com/api3dao/logos/main/raw/symbols/mati-cx.svg" width="32" height="32" />   |
| PYTH                  | <img src="https://raw.githubusercontent.com/api3dao/logos/main/raw/symbols/pyth.svg" width="32" height="32" />  |
| WOO                   | <img src="https://raw.githubusercontent.com/api3dao/logos/main/raw/symbols/woo.svg" width="32" height="32" />   |
| MATIC Exchange Rate   | <img src="https://raw.githubusercontent.com/api3dao/logos/main/raw/symbols/matic-exchange-rate.svg" width="32" height="32" />   |
| NG                    | <img src="https://raw.githubusercontent.com/api3dao/logos/main/raw/symbols/ng.svg" width="32" height="32" />   |
| QQQ                   | <img src="https://raw.githubusercontent.com/api3dao/logos/main/raw/symbols/qqq.svg" width="32" height="32" />   |
| PYPL                  | <img src="https://raw.githubusercontent.com/api3dao/logos/main/raw/symbols/pypl.svg" width="32" height="32" />   |
